### PR TITLE
fix deps for use with npx

### PR DESCRIPTION
**Pull request by mhdawson**
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>

### CODE REVIEW

**Review by rodion-arr — APPROVED** [review]
Maybe it is good place to update Nodejs version in `engines` as we are running tests on 10+?
```
"engines": {
    "node": "^14 || ^13 || ^12 || ^11 || ^10 || ^8 || ^6"
  }
```

**Comment by mhdawson** [comment]
@rodion-arr added

**Comment by ljharb** [comment]
I'd suggest running `npx ls-engines --save` to ensure it matches the dependency graph :-)

**Comment by mhdawson** [comment]
@ljharb done. Interestingly it flagged that some dependency needs at least 10.19

**Pull request merged**
